[package]
name = "lib-error"
version = "0.1.0"
authors = ["Marius Seritan <git@winding-lines.com>"]

[dependencies]
error-chain = "0.12"
diesel = "*"
sys-info = "*"
actix-web = "0.7"
reqwest = "0.8"
regex = "1.0"

[dependencies.tantivy]
git = "https://github.com/tantivy-search/tantivy"
rev = "2649c8a7158e6b8c504aa6b43e5af98da8d2c420"
features = ["mmap"]
