image: 'rust:latest'

stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt
  RUST_SODIUM_USE_PKG_CONFIG: "true"

before_script:
  - docker info


release:
  stage: build
  script:
    - docker build -t weaver .
  only:
    - master

