image: 'rust:latest'

stages:
  - test
  - doc
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y sqlite3 libsqlite3-dev libncurses5-dev libncursesw5-dev cmake

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

pages:
  stage: doc
  script:
    - cargo doc --all --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url='weaaver'">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

release:
  stage: build
  script:
    - cargo build --release
    - mv target/release/weaver release
  artifacts:
    paths:
      - release
  only:
    - master

cache:
  paths:
    - apt/
    - cargo/
    - target/
