image: 'docker:latest'

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind 
   
before_script:
  - docker info


release:
  stage: build
  script:
    - docker build -t weaver .
  only:
    - master

