[package]
name = "weaver"
version = "0.1.2"
description = "Manage actions, flows and milestones"
authors = ["Marius Seritan <git@winding-lines.com>"]

[dependencies]
clap = "2.30.0"
error-chain = "0.11.0"
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
walkdir = "2"
log = "0.4"
env_logger = "0.5"

