[package]
name = "weaver"
version = "0.3.1"
description = "Manage actions, flows and milestones"
authors = ["Marius Seritan <git@winding-lines.com>"]

[workspace]
members = ["weaver-error", "weaver-rpc", "weaver-db", "weaver-index"]

[dependencies]
clap = "2.30.0"
termion = "1.5"
clipboard = "0.4"

chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
walkdir = "2"

log = "0.4"
env_logger = "0.5"

gotham = "0.2.1"
gotham_derive = "0.2.1"
hyper = "0.11"
futures = "0.1"
mime = "0.3"
daemonize = {git = "https://github.com/winding-lines/daemonize"}

weaver-rpc = {path = "weaver-rpc"}
weaver-error = {path = "weaver-error"}
weaver-db = {path = "weaver-db"}
weaver-index = {path = "weaver-index"}


[dependencies.cursive]
git = "https://github.com/gyscos/Cursive"
rev = "2729e77838b2312054251"
# version = "0.9"

[dependencies.cursive_table_view]
git = "https://github.com/winding-lines/cursive_table_view"
rev = "f8e5d7096af6a03948"
# default-features = false
# features = ["blt-backend"]

