[package]
name = "weaver"
version = "0.1.4"
description = "Manage actions, flows and milestones"
authors = ["Marius Seritan <git@winding-lines.com>"]

[dependencies]
clap = "2.30.0"
cursive = "0.8"
cursive_table_view = {git = "https://github.com/winding-lines/cursive_table_view"}
termion = "1.5"

error-chain = "0.11.0"
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
walkdir = "2"

log = "0.4"
env_logger = "0.5"

gotham = "0.2.0"
gotham_derive = "0.2.0"
hyper = "0.11"
futures = "0.1"
mime = "0.3"
