[package]
name = "weaver"
version = "0.2.0"
description = "Manage actions, flows and milestones"
authors = ["Marius Seritan <git@winding-lines.com>"]

[dependencies]
clap = "2.30.0"
termion = "1.5"
clipboard = "0.4"


error-chain = "0.11"
diesel = { version = "1.0.0", features = ["sqlite"] }
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
walkdir = "2"

log = "0.4"
env_logger = "0.5"

gotham = "0.2.0"
gotham_derive = "0.2.0"
hyper = "0.11"
futures = "0.1"
mime = "0.3"
daemonize = {git = "https://github.com/winding-lines/daemonize"}

[dependencies.cursive]
git = "https://github.com/gyscos/Cursive"
rev = "b34fb14957f877"
# version = "0.8"
# default-features = false
# features = ["blt-backend"]

[dependencies.cursive_table_view]
git = "https://github.com/winding-lines/cursive_table_view"
rev = "d494c29921"
# default-features = false
# features = ["blt-backend"]

