---
apiVersion: v1
kind: Service
metadata:
  name: weaver
  labels:
    app: weaver
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: weaver
