[package]
name = "lib-ai"
version = "0.1.0"
authors = ["Marius Seritan <git@winding-lines.com>"]


[dependencies]
url = "1"
log = "*"

lib-error = {path = "../lib-error"}
lib-goo = {path = "../lib-goo"}
